### ISSUE TITLE
SOLVED: Strange behaviour in Firefox and Chrome, using Confirm with question mark and double quotes

### ISSUE THREAD

**Issue by jczerosb** [notiflix/Notiflix#1]
I have a message like Knowledge of Operation - This operation "can not be reverted" - Do you Confirm?
Don´t know how, but in FF & Chrome message gets rendered as:
Knowledge of Operation - This operation `"can ?not be reverted"` - Do you Confirm
When check source code with browser F12 it looks correct.
If I go to Notiflix Live Demo, it shows fine.

Here an image what I´m getting
![Screenshot_2019-04-08 Screenshot](https://user-images.githubusercontent.com/42658793/55739486-8a19f400-59ff-11e9-910d-785de3c83142.png)
Image from Live demo
![Screenshot_2019-04-08 Notiflix a JavaScript library for client-side non-blocking notifications ](https://user-images.githubusercontent.com/42658793/55739698-eed54e80-59ff-11e9-9fd7-a5672ee2712e.png)

Code I´m using
`<script type="text/javascript">
    function zNotiflixConfirm() {
      Notiflix.Confirm.Init({ width: '350px', titleMaxLength: 100, messageMaxLength: 250, rtl: true })
      Notiflix.Confirm.Show('Agreement Confirmation', 'Knowledge of Operation - This operation "can not be reverted" - Do you Confirm?', 'Yes', 'No', function () { alert('Thank you.'); });
    }
</script>`

**Comment by notiflix** [comment]
Hello, firstly thanks for using Notiflix.

Your issue is all about your Init options. 

You defined the RTL option as "Ture". Its defined as "False" by default.

If you website don't using "Arabic", "Persian/Farsi" or etc. languages that use right to left; you don't need to set RTL as "True".

You can define RTL option to "False" or delete on your init; your issue will be solved.

Thanks.

---

Your Init Code has to be like that:
` Notiflix.Confirm.Init({
width: '350px',
titleMaxLength: 100,
messageMaxLength: 250,
});`
