### ISSUE TITLE
Button off screen

### ISSUE THREAD

**Issue by dingetje** [notiflix/Notiflix#12]
When the close button is off screen (i.e. on a small phone), there is no way to close a Report notification.

**Comment by furcan** [comment]
Hi, thanks for using Notiflix.

You can use the "width" option to set width of the Report module.

Feel free to look at the documentation. 

Thanks.

**Comment by dingetje** [comment]
This is not a question, I don't like the way you close reported issues.
I already have width at 100% and yet on small screens this is not enough and then your dead in the water. As a minimum you could add a touch event on the whole popup to close.

**Comment by furcan** [comment]
Hello again,

First of all, I'm sorry I couldn't give you an answer to your expectations.

If you can also share a size, such as the width and height of the screen in pixels, it would be better.

Also,

If you have elements in the document that do not fit horizontally on the screen and are overflowing, this will ruin your expectation of 100% units of measure.

Thanks.

**Comment by dingetje** [comment]
Look, it's a simple issue. Pick a phone with a ridiculous small screen, say 240x320 and then display a notiflix Report popup with a long message. The Close button will be off screen. Now what?

**Comment by furcan** [comment]
Hi again,

There is some screenshots about that resolution below.

<img width="365" alt="Screen Shot 2020-01-07 at 09 51 49" src="https://user-images.githubusercontent.com/49978011/71875663-e5ffdd80-3135-11ea-99fc-50a5c5278bfd.png">

So;

240x320px is a really small screen and if you wanna use Notiflix Report module on this device, you have to limit some options.
An example of initialize code as below.

`Notiflix.Report.Init({
    svgSize: "60px",
    titleFontSize: "13px",
    messageFontSize: "10px",
    buttonFontSize: "11px",
    messageMaxLength: 190,
});`

<img width="365" alt="Screen Shot 2020-01-07 at 09 59 32" src="https://user-images.githubusercontent.com/49978011/71875787-337c4a80-3136-11ea-8263-e7464b39dcdd.png">

If this solution does not enough for your expectation (long messagea), 
I recommend to create your own solution for this, because the resolution and the device are too specific. Notiflix can not do more about that request.

Thank you.

**Comment by dingetje** [comment]
Thanks for looking into this, but You still don't understand the issue at hand...

When the close button is OFF SCREEN (because the message is too long, the font size too big, etc) then there is no way to close the Report notification. All I'm asking is to have a way to close the Report popup, for instance by clicking the window or the icon.

**Comment by furcan** [comment]
Hi again. 

Your request is so personal and unfortunately there is no possibility to do something.

Also Notiflix is an open source project. You can fork Notiflix and you can create your solution about your request if you wish.

Thanks.
