### ISSUE TITLE
[FEAT] - Notiflix production console error and warning

### ISSUE THREAD

**Issue by swoorr** [notiflix/Notiflix#57]
### Is your feature request related to a problem? Please describe.
When i was deployed to production, it was be continue show console error and info and warning

### Describe the solution you'd like
May be production config, show console errors: false 

### Describe alternatives you've considered
Or may be production implementation always remove console lines 

### Additional context
<img width="1109" alt="Screen Shot 2022-07-25 at 15 04 42" src="https://user-images.githubusercontent.com/4634368/180773727-ff396efa-9345-4f2b-b61c-e24babb07990.png">

**Comment by furcan** [comment]
Hi @swoorr ,

You are getting this log(actually this is a runtime error on your code) because you are calling the `remove()` method twice for no reason. Notiflix prevents these unnecessary calls and shows this log to the clients.

You can please double-check your implementation, or you can share your code as a snippet so that I can give you more info.

Thanks,
Furkan.
