### ISSUE TITLE
[BUG] - Can't type on Confirm.prompt()

### ISSUE THREAD

**Issue by beans518** [notiflix/Notiflix#72]
### Describe the bug
For some reason, I cannot type inside the textarea of Notiflix.Confirm.prompt and I don't know why.

### To Reproduce
1. Click a button that will appear the prompt

### Expected behavior
I should type inside the textarea and then save it as a remarks, but the main issue is not letting me type.

### Desktop (please complete the following information):
 - Windows
 - Browser : Edge
 - Version of notiflix: notiflix-3.2.6

### Additional context
Here is my code
![sss](https://github.com/notiflix/Notiflix/assets/126551848/c542e303-565c-435d-9314-fdf1198ce053)

**Comment by furcan** [comment]
Hello @beans518,

First of all, if you are not checking anything regarding the client's answer to move forward with the okCallback, maybe you can just use `Notiflix.Confirm.show()`

or for your code with prompt,

```js
Notiflix.Confirm.prompt(
  'Title',
  'Question?',
  '', // leave as an empty string if you are not willing to have prefilled answer
  'Ok',
  'Cancel',
  function okCb(clientAnswer) {
    console.log('Client answer is: ' + clientAnswer);
  },
  function cancelCb(clientAnswer) {
    console.log('Client answer was: ' + clientAnswer);
  },
  {
    // Custom options
  },
);
```

I am closing this ticket because I believe, the case that you presented is not related to Notiflix, there might be something else. 

Thanks,
Furkan
