### ISSUE TITLE
Confirm.show() not displayed when called from dialog is modal

### ISSUE THREAD

**Issue by thebluemountain** [notiflix/Notiflix#81]
hi,

first of all, thank you for making this library available for other developers.
starting to use it, i was intending to use the Confirm.show () from a modal dialog and was expecting to have the confirmation dialog appearing in front.
However, it seems i have to close the dialog to see, under, the confirmation still being displayed.

Q: do you have any advice on the use or configuration to allow for the Confirm.show() to be accessible, in front of the dialog ?

Thank you,

**Comment by furcan** [comment]
Hello,

you are welcome, and thank you for your kind words.

You can please focus on the `zindex` property/option. I presume you will have a solution. 
https://github.com/notiflix/Notiflix#notiflix-confirm-module-default-options
Otherwise, you can please re-open this ticket with some extra information such as screenshots, code blocks etc...

Best wishes,
Furkan

**Comment by thebluemountain** [comment]
hi,

i had been trying with that zindex configuration but it does not seem effective when used in such context (using a dialog in model fashion) but was unsuccessful at reaching the outcome i was expecting

see the sample html page with a dialog carrying a z-index value and configuration of a confirm that carries greater value.
the Confirm UI remains under and both keyboard nor mouse event remain not accessible for the Confirm (html elements)

originally, both dialog and Confirm options

 were not carrying z-index specification ... with no change from user's behavior perspective
 
[notify.html.txt](https://github.com/notiflix/Notiflix/files/13997210/notify.html.txt)
