### ISSUE TITLE
[FEAT] - Confirm to be selected from a dropdown

### ISSUE THREAD

**Issue by shanpuzzo** [notiflix/Notiflix#85]
Hello and thanks for this beautiful library.
I have one question, I see that confirm.prompt asks the user a text string and I use it wherever needed; 
however, i'd like to have the possibility to insert a select box to have the user select from the given options.
Would that be possible?
Thanks in advance

**Comment by furcan** [comment]
Hello,
you are welcome.

You have only one solution for this request:

- you can try to disable the `plainText`(https://github.com/notiflix/Notiflix#notiflix-confirm-module-default-options) option as `false` since it is defaulted as `true` and,
- Use the `Notiflix.Confirm.show()` https://github.com/notiflix/Notiflix#show method with the description(the second argument) content will be your area to use the stringified HTML content as you want.
- Disabling the OK or Cancel button due to your custom logic is not applicable. Still, you can create workarounds using JavaScript APIs to add/remove `disable` attributes to these buttons by your logic.

```ts
Notiflix.Confirm.show(
  'Title',
  '<h1>HTML</h1>',
  'Yes',
  'No',
  function okCb() {
    alert('Yes');
  },
  function cancelCb() {
    alert('No');
  },
  {
    plainText: false,
  },
);
```

Thank you,
Furkan
