### ISSUE TITLE
[BUG] - cannot change messageColor

### ISSUE THREAD

**Issue by udin-ordinari** [notiflix/Notiflix#88]
hi notiflix team
i can not change the Processing text to white
iam following as your instruction in documentation but still not working.
-> Notiflix.Loading.circle('Processing...', {messageFontSize: '25px', messageColor: '#fff',});

**Comment by furcan** [comment]
Hello,

The default colour for the Loading module is already white and it is working as it should be since version 1.

https://notiflix.github.io/loading

You can please provide more context regarding your implementation details to assess what is working or not. You can please also provide codepen or something to reproduce or please provide screen records to express what you mean.

Thank you.
